language: python
python:
  - "2.7"
# command to install dependencies
before_install: gem install asciidoctor
install: sudo apt-get install asciidoc -qq
# command to run tests
script:  asciidoc --version ; asciidoctor --version